# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "cocoapods"
gem 'cocoapods-patch', :git => 'https://github.com/DoubleSymmetry/cocoapods-patch.git'